# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts \
 && npm run build

# Final image
FROM node:lts-alpine AS runtime
WORKDIR /app
COPY --from=builder /app/build ./build
COPY package.json ./
# install production dependencies
RUN npm install --omit=dev --ignore-scripts

# Default command to start the MCP server over stdio
ENTRYPOINT ["node", "build/index.js"]
